In [6]:
!pip install statsmodels pmdarima pandas matplotlib seaborn

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting pmdarima
  Downloading pmdarima-2.1.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.0)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from statsmodels) (2.4.1)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (25.0)
Collecting joblib>=0.11 (from pmdarima)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting Cython!=0.29.18,!=0.29.31,>=0.29 (from pmdarima)
  Downloading cython-3.2.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Collecting scikit-learn>=0.22 (from pmdarima)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: urllib3 in /home/codespace/.local/lib/python3.12/site-packages (from pmdarima) (2.5.0)
Requirement already satisfied: setuptools!=50.0.0,>=42 in /home/codespace/.local/lib/python3.12/site-packages (from pmdarima) (80.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=0.22->pmdarima)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading statsmodels-0.14.6-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 26.6 MB/s  0:00:00eta 0:00:01
Downloading pmdarima-2.1.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (689 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 689.1/689.1 kB 22.1 MB/s  0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 39.5 MB/s  0:00:00m0:00:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading cython-3.2.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 35.7 MB/s  0:00:00
Downloading fonttools-4.62.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 33.5 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 24.5 MB/s  0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 27.5 MB/s  0:00:00 eta 0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 32.7 MB/s  0:00:00m0:00:01
Downloading scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 31.6 MB/s  0:00:01m0:00:0100:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, pyparsing, pillow, patsy, kiwisolver, joblib, fonttools, Cython, cycler, contourpy, scikit-learn, matplotlib, statsmodels, seaborn, pmdarima
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16 [pmdarima]/16 [pmdarima]ls]]
Successfully installed Cython-3.2.4 contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.0 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 patsy-1.0.2 pillow-12.1.1 pmdarima-2.1.1 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 statsmodels-0.14.6 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
## imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
import pmdarima as pm  # auto_arima

from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')

### 1 - Pré-processamento

In [9]:
# carregando arquivos
ipca = pd.read_csv('ipca.csv', parse_dates=['data'], index_col='data')
cpi  = pd.read_csv('us_cpi.csv', parse_dates=['date'], index_col='date')
fx   = pd.read_csv('usd_brl_monthly.csv', parse_dates=['data'], index_col='data')

In [ ]:
# frequência mensal
ipca = ipca.asfreq('MS')  # 'MS' = início do mês
cpi  = cpi.asfreq('MS')
fx   = fx.asfreq('MS')

In [24]:
fx.head()

            valor_ultimo_mes
data
2000-01-01            1.8024
2000-02-01            1.7685
2000-03-01            1.7473
2000-04-01            1.8067
2000-05-01            1.8266

In [26]:
# Seleciona apenas date + coluna do número antes do merge
cpi_clean = cpi[['value']].rename(columns={'value': 'us_cpi'})
ipca_clean = ipca[['valor']].rename(columns={'valor': 'br_ipca'})
fx_clean = fx[['valor_ultimo_mes']].rename(columns={'valor_ultimo_mes': 'br_fx'})

In [27]:
df = ipca_clean.join(cpi_clean, how='left').join(fx_clean, how='left')

In [28]:
df.head()

            br_ipca  us_cpi   br_fx
data
2000-01-01     0.62   168.8  1.8024
2000-02-01     0.13   169.8  1.7685
2000-03-01     0.22   171.2  1.7473
2000-04-01     0.42   171.3  1.8067
2000-05-01     0.01   171.5  1.8266

### 2 - Análise de estacionariedade (ADF)

### 3 - Seleção de ordem (ACF/PACF + AIC)

### 4 - Treino ARIMAX → Previsão → Avaliação